### ISSUE TITLE
Enhancements to API Dashboard UI

### ISSUE THREAD

**Issue by GioGio03** [TechShreyash/CloudflareWorker#3]
I've made some improvements to the UI of the API Dashboard to enhance its style and user experience. The changes include a modern design, improved responsiveness for both desktop and mobile, but I cant open pr atm so this was the html code; https://srcb.in/jECLBtE72C

**Comment by TechShreyash** [comment]
Oh thanks, i will check it out and commit to the main repo

**Comment by GioGio03** [comment]
No worries I tried my very best and I changed it a bit: https://srcb.in/UZbrcL0U4k. With "**Add more sample requests and responses**" I mean showing users how they can interact with your AnimeDex API.

For instance:
- Searching for an anime by name:
- Request: /search/one-piece
- Response:
```json
{
  "results": [
    {
      "title": "One Piece",
      "img": "https://gogocdn.net/images/anime/One-piece.jpg",
      "link": "https://gogoanime3.net/category/one-piece",
      "id": "one-piece",
      "releaseDate": "Released: 1999"
    },
    // ... (more results)
  ]
}
```

- **title**: The title of the anime.
- **img**: The URL to the anime's image.
- **link**: The link to the anime on GogoAnime.
- **id**: A unique identifier for the anime.
- **releaseDate**: The release date or year of the anime.

**Comment by TechShreyash** [comment]
thats nice 👍

**Comment by GioGio03** [comment]
thanks ;)

**Comment by GioGio03** [comment]
Lemme know if you will add it 👍🏻 have a nice day

**Comment by TechShreyash** [comment]
Yeah i will

**Comment by TechShreyash** [comment]
> https://srcb.in/UZbrcL0U4k

the urls you provided arent opening

**Comment by TechShreyash** [comment]
Docs Added To AnimeDexApi, Thanks For The Code

Check At https://api.anime-dex.workers.dev

**Comment by GioGio03** [comment]
Nice, you are welcome
